version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: tq-postgres
    environment:
      POSTGRES_DB: taskqueue
      POSTGRES_USER: taskqueue
      POSTGRES_PASSWORD: taskqueue
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskqueue"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-alpine
    container_name: tq-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: ./backend
    container_name: tq-app
    environment:
      DB_HOST: postgres
      DB_NAME: taskqueue
      DB_USER: taskqueue
      DB_PASS: taskqueue
      REDIS_HOST: redis
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  dashboard:
    build: ./dashboard
    container_name: tq-dashboard
    ports:
      - "3000:80"
    depends_on:
      - app

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: tq-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    depends_on:
      - app

  grafana:
    image: grafana/grafana:10.4.0
    container_name: tq-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  zipkin:
    image: openzipkin/zipkin:3
    container_name: tq-zipkin
    ports:
      - "9411:9411"

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
